#!/bin/sh

export PNPM_HOME="$HOME/Library/pnpm"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
export PATH="$PNPM_HOME:$PATH"

echo "Running pre-push checks (Biome on changed files vs main, typecheck, test)..."
pnpm precheck:push
