query ExpenseDashboard($motorcycleId: String!) {
  expenseDashboard(motorcycleId: $motorcycleId) {
    currency
    currentYearTotal
    previousYearTotal
    allTimeTotal
    expenseCount
    monthlyBuckets {
      month
      year
      categories {
        category
        total
      }
      total
    }
    categoryTotals {
      category
      total
    }
    currencies {
      currency
      currentYearTotal
      previousYearTotal
      allTimeTotal
      expenseCount
      monthlyBuckets {
        month
        year
        categories {
          category
          total
        }
        total
      }
      categoryTotals {
        category
        total
      }
    }
  }
}
