query GetComments($rideId: ID, $routeId: ID, $groupRideId: ID, $first: Int, $after: String) {
  getComments(rideId: $rideId, routeId: $routeId, groupRideId: $groupRideId, first: $first, after: $after) {
    comments {
      id
      text
      createdAt
      flaggedCount
      parentCommentId
      author {
        id
        displayName
        publicUsername
        avatarUrl
      }
      replies {
        id
        text
        createdAt
        flaggedCount
        parentCommentId
        author {
          id
          displayName
          publicUsername
          avatarUrl
        }
      }
    }
    hasNextPage
    endCursor
    totalCount
  }
}
