query MyRides($first: Int, $after: String, $motorcycleId: String) {
  myRides(first: $first, after: $after, motorcycleId: $motorcycleId) {
    edges {
      node {
        id
        status
        name
        startedAt
        endedAt
        distanceM
        maxSpeedMps
        avgSpeedMps
        elevationGain
        pausedDurationS
        autoPausedDurationS
        durationS
        motorcycleId
        routeThumbnailUri
        routePolyline
        region
        gpsQuality
      }
      cursor
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
