query SavedRoutes($first: Int, $after: String) {
  savedRoutes(first: $first, after: $after) {
    edges {
      node {
        id
        name
        polyline
        distanceM
        elevationGainM
        surfaceType
        isMotovaultPick
        ratingAvg
        ratingCount
        commentCount
        createdAt
        startLat
        startLng
        contributor {
          id
          displayName
          publicUsername
          avatarUrl
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
