// Auto-generated by `supabase gen types typescript --local`
// Do NOT edit manually. Run `pnpm db:types` to regenerate.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      // Will be populated by supabase gen types
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
