-- Add a `source` column to social_post_queue to distinguish manually-seeded
-- rows (via fill-queue.ts) from Gemini-autodrafted rows (via the Worker's
-- scheduled() handler when the queue is empty for a given slot).
--
-- Column is nullable with no default — this is a metadata-only change in
-- PostgreSQL and does not rewrite the table. Safe to run on the live table
-- that's actively queried by the Cloudflare cron.
--
-- Values used by the Worker:
--   NULL or 'manual'         — seeded via scripts/fill-queue.ts
--   'gemini-autodraft'       — generated by Worker.scheduled() via Gemini 3 Flash Preview

ALTER TABLE public.social_post_queue
  ADD COLUMN IF NOT EXISTS source TEXT;

COMMENT ON COLUMN public.social_post_queue.source IS
  'Origin of this row: NULL or ''manual'' for fill-queue.ts seeded rows, ''gemini-autodraft'' for Worker-generated rows.';
