export const COUNTRY_CONTINENT: Record<string, string> = {
  // Europe
  IT: 'Europe',
  FR: 'Europe',
  CH: 'Europe',
  ES: 'Europe',
  AT: 'Europe',
  DE: 'Europe',
  PT: 'Europe',
  GR: 'Europe',
  NO: 'Europe',
  IS: 'Europe',
  GB: 'Europe',
  IE: 'Europe',
  RO: 'Europe',
  HR: 'Europe',
  CZ: 'Europe',
  PL: 'Europe',
  HU: 'Europe',
  SE: 'Europe',
  DK: 'Europe',
  FI: 'Europe',
  BG: 'Europe',
  SI: 'Europe',
  SK: 'Europe',
  NL: 'Europe',
  BE: 'Europe',
  BA: 'Europe',
  RS: 'Europe',
  ME: 'Europe',
  AL: 'Europe',
  MK: 'Europe',
  // Americas
  US: 'Americas',
  CA: 'Americas',
  MX: 'Americas',
  AR: 'Americas',
  CL: 'Americas',
  PE: 'Americas',
  BR: 'Americas',
  CO: 'Americas',
  EC: 'Americas',
  BO: 'Americas',
  CR: 'Americas',
  // Asia & Pacific
  JP: 'Asia & Pacific',
  NZ: 'Asia & Pacific',
  AU: 'Asia & Pacific',
  TH: 'Asia & Pacific',
  VN: 'Asia & Pacific',
  IN: 'Asia & Pacific',
  NP: 'Asia & Pacific',
  KR: 'Asia & Pacific',
  TW: 'Asia & Pacific',
  PH: 'Asia & Pacific',
  ID: 'Asia & Pacific',
  MY: 'Asia & Pacific',
  // Africa & Middle East
  MA: 'Africa & Middle East',
  ZA: 'Africa & Middle East',
  NA: 'Africa & Middle East',
  JO: 'Africa & Middle East',
  TZ: 'Africa & Middle East',
  KE: 'Africa & Middle East',
  AE: 'Africa & Middle East',
  OM: 'Africa & Middle East',
};

export const CONTINENT_ORDER = [
  'Europe',
  'Americas',
  'Asia & Pacific',
  'Africa & Middle East',
] as const;
